---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Check for jsvc binary
  ansible.builtin.command: which jsvc
  ignore_errors: true
  register: jsvc_binary
  changed_when: jsvc_binary.rc
  tags: jsvc

- name: Compile jsvc on remote host when missing
  ansible.builtin.include_tasks: compile-jsvc.yml
  when:
    - "'jsvc' not in ansible_facts.packages"
    - jsvc_binary.rc != 0
  tags: jsvc
