---
- name: Gather Package Facts
  ansible.builtin.package_facts:
    manager: auto

- name: Check for jsvc Binary
  ansible.builtin.shell: command -v jsvc
  ignore_errors: true
  register: jsvc_binary
  changed_when: jsvc_binary.rc !=0

- name: Compile jsvc on Remote Host
  ansible.builtin.include_tasks: compile-jsvc.yml
  when:
    - "'jsvc' not in ansible_facts.packages"
    - jsvc_binary.rc != 0
