---
- name: Converge
  hosts: all
  vars:
    jsvc_src_version: "{{ lookup('env', 'JSVC_VERSION') }}"
    jsvc_tar_src: "./files/commons-daemon-{{ jsvc_src_version }}-native-src.tar.gz"
    jsvc_tar_src_remote: false
  pre_tasks:
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      changed_when: false

  tasks:
    - name: "Include ansible-role-jsvc"
      ansible.builtin.include_role:
        name: "ansible-role-jsvc"
