---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - image: ${MOLECULE_IMAGE:-trfore/docker-debian11-systemd}
    name: ${MOLECULE_NAME:-instance}
    command: ${MOLECULE_COMMAND:-""}
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  env:
    JSVC_VERSION: ${JSVC_VERSION:-"1.4.0"}
verifier:
  name: ansible
scenario:
  create_sequence:
    - create
  check_sequence:
    - destroy
    - create
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
