---
- name: Verify
  hosts: all
  gather_facts: false
  vars:
    jsvc_src_version: "{{ lookup('env', 'JSVC_VERSION') }}"
  tasks:
    - name: Test | Get Binary File Info
      ansible.builtin.stat:
        path: /usr/bin/jsvc
      register: file_info

    - name: Test | Check jsvc Binary Exists
      ansible.builtin.assert:
        that:
          - file_info.stat.exists
        quiet: true

    - name: Test | Pull jsvc Version
      ansible.builtin.shell: |
        set -o pipefail
        jsvc -home $(realpath /usr/bin/java | sed 's:/\(jre/bin\|bin\)/java::') -help | grep 'jsvc (Apache Commons Daemon)'
      args:
        executable: /bin/bash
      register: jsvc_version
      changed_when: jsvc_version.rc != 0

    - name: Test | Assert jsvc Version Matches Source Code
      ansible.builtin.assert:
        that: exe_ver == src_ver
      vars:
        exe_ver: '{{ jsvc_version.stdout | regex_search("\d\.\d\.\d") }}'
        src_ver: "{{ jsvc_src_version }}"
