name: CI
on:
  pull_request:
    branches: ["*"]
    paths-ignore:
      - "**.md"
      - "LICENSE"
  workflow_dispatch:

jobs:
  lint:
    uses: trfore/ansible-role/.github/workflows/lint_ansible.yml@main

  test:
    needs:
      - lint
    strategy:
      fail-fast: false
      matrix:
        distro:
          [
            centos8,
            centos9,
            debian10,
            debian11,
            ubuntu2004,
            ubuntu2204,
            ubuntu2404,
          ]
        molecule_scenario: ["-s default"]
    uses: trfore/ansible-role/.github/workflows/test_ansible.yml@main
    with:
      distro: ${{ matrix.distro }}
      molecule_scenario: ${{ matrix.molecule_scenario }}

  check:
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    steps:
      - run: >-
          python -c "assert set([
          '${{ needs.lint.result }}',
          '${{ needs.test.result }}',
          ]) == {'success'}"
