name: ci
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci.yml'
      - '.github/workflows/release.yml'
      - 'defaults/**'
      - 'files/**'
      - 'handlers/**'
      - 'meta/**'
      - 'molecule/**'
      - 'tasks/**'
      - 'vars/**'
      - '.yamllint'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/ci.yml'
      - '.github/workflows/release.yml'
      - 'defaults/**'
      - 'files/**'
      - 'handlers/**'
      - 'meta/**'
      - 'molecule/**'
      - 'tasks/**'
      - 'vars/**'
      - '.yamllint'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: check out codebase
        uses: actions/checkout@v3

      - name: lint code
        run: yamllint .

  test:
    needs: [lint]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro: [centos8, debian10, debian11, ubuntu2004, ubuntu2204]
    steps:
      - name: check out codebase
        uses: actions/checkout@v3

      - name: setup python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: run molecule test
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          # MOLECULE_COMMAND: ''
          MOLECULE_IMAGE: trfore/docker-${{ matrix.distro }}-systemd
          MOLECULE_NAME: ${{ matrix.distro }}
          # MOLECULE_PLAYBOOK: ''
