name: CI
on:
  workflow_dispatch:
  pull_request:
    branches: ["*"]
    types: [opened]
    paths-ignore:
      - "LICENSE"
      - "README.md"

jobs:
  lint_ansible:
    uses: trfore/ansible-role/.github/workflows/lint_ansible.yml@main

  molecule_test:
    needs:
      - lint_ansible
    strategy:
      fail-fast: false
      matrix:
        distro: [centos8, debian10, debian11, ubuntu2004, ubuntu2204]
        experimental: [false]
        molecule_scenario: ["-s default"]
    uses: trfore/ansible-role/.github/workflows/test_ansible.yml@main
    with:
      distro: ${{ matrix.distro }}
      experimental: ${{ matrix.experimental }}
      molecule_scenario: ${{ matrix.molecule_scenario }}
