name: dependabot auto-approve and merge
on: pull_request
permissions:
  contents: write
  pull-requests: write
env:
  PR_URL: ${{ github.event.pull_request.html_url }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Auto-approve Dependabot PR
        run: gh pr review --approve "$PR_URL"

      - name: Auto-merge Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
